apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: poller-hpa
  namespace: default
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-poller-deployment
  targetCPUUtilizationPercentage: {{ .Values.scaling.maxCPUUtilizationPercent }}