apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-poll
spec:
  selector:
    app: {{ .Release.Name }}-poller
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
        